export default {
  SET_ALERT: "SET_ALERT",
  REMOVE_ALERT: "REMOVE_ALERT",
  LOGGED_USER: "LOGGED_USER",
  USER_LOGGED: "USER_LOGGED",
  LOGIN_FAIL: "LOGIN_FAIL",
  REGISTER_FAIL: "REGISTER_FAIL",
  USER_REGISTERED: "USER_REGISTERED",
  ROOMED: "ROOMED",
};
